# Generated by Django 4.1.7 on 2023-03-29 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("cre", "create"),
                            ("upd", "update"),
                            ("del", "delete"),
                            ("dea", "deactivate"),
                            ("act", "activate"),
                            ("inv", "invite"),
                            ("exp", "expire"),
                        ],
                        max_length=3,
                    ),
                ),
                ("target", models.BigIntegerField(null=True)),
                (
                    "target_name",
                    models.CharField(
                        choices=[
                            ("dri", "driver"),
                            ("use", "user"),
                            ("gro", "gross"),
                            ("car", "carrier"),
                            ("veh", "vehicle"),
                            ("tra", "trailer"),
                            ("lin", "invite link"),
                        ],
                        max_length=3,
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
