# Generated by Django 4.1.7 on 2023-03-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailer",
            name="samsara_id",
            field=models.IntegerField(null=True),
        ),
    ]
