# Generated by Django 4.1.7 on 2023-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_trailer_samsara_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailer",
            name="samsara_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
