# Generated by Django 4.1.7 on 2023-03-31 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_trailer_samsara_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("m", "move"), ("s", "stop")], max_length=1
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trailer_log",
                        to="api.trailer",
                    ),
                ),
            ],
        ),
    ]
