# Generated by Django 4.2 on 2023-04-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_roadpoint_trailerlog_latitude_trailerlog_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailerImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="logistics/images")),
                (
                    "trailer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trailer_image",
                        to="api.trailer",
                    ),
                ),
            ],
        ),
    ]
